[tool.ruff]
line-length = 99
exclude = ["./docker.py"]

[tool.ruff.lint]
select = ["E", "F", "W", "I", "TID251"]
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.lint.isort]
extra-standard-library = ["packaging", "pkg_resources", "setuptools"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "nextgisweb-env-lib",
    "nextgisweb-comp",
    "first-party",
    "local-folder",
]

[tool.ruff.lint.isort.sections]
"nextgisweb-env-lib" = ["nextgisweb.env", "nextgisweb.lib"]
"nextgisweb-comp" = ["nextgisweb"]

[tool.ruff.lint.flake8-tidy-imports.banned-api]
"typing_extensions.Annotated".msg = "Import Annotated from typing directly"