[tool.black]
line-length = 99

[tool.ruff]
line-length = 99
select = ["E", "F", "W", "I"]
ignore = ["E501"]
exclude = ["./docker.py"]

[tool.ruff.per-file-ignores]
"__init__.py" = ["F401"]

[tool.ruff.isort]
extra-standard-library = ["packaging", "pkg_resources", "setuptools"]
section-order = [
    "future",
    "standard-library",
    "third-party",
    "nextgisweb-env-lib",
    "nextgisweb-comp",
    "first-party",
    "local-folder",
]

[tool.ruff.isort.sections]
"nextgisweb-env-lib" = ["nextgisweb.env", "nextgisweb.lib"]
"nextgisweb-comp" = ["nextgisweb"]
